### ISSUE TITLE
Automatically become lower-privilege user

### ISSUE THREAD

**Issue by EtiennePerot** [cdown/ansible-aur#3]
Ansible either expects to SSH into machines as `root`, or to become `root` after SSHing through some mechanism e.g. `sudo`.<sup>[1]</sup> However, neither `pacaur`, `yaourt`, or `makepkg` allow executing operations as `root`.<sup>[2]</sup> This means that the example in README.md currently do not work; they will fail with "you cannot perform this operation as root".

The only way I've found to use ansible-aur in a playbook that also uses other modules (e.g. Ansible's own `pacman` or `package` module) requires doing something like this:

```yaml
- name: install sudo
  package:
    name: sudo
    state: latest
  register: install_sudo

- name: create build user
  user:
    name: pacaur-builder
    ...
  register: create_build_user

- name: allow build user to sudo pacman
  when:
    - install_sudo|succeeded
    - create_builder_user|succeeded
  file:
    path: /etc/sudoers.d/allow-build-user-to-sudo-pacman
    contents: "pacaur-builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    ...
  register: allow_build_user_to_sudo_pacman
```

And then each `aur` invocation has to include `when` + `become` + `become_user` directives:

```yaml
- name: install a package example
  when: allow_build_user_to_sudo_pacman|succeeded
  become: yes
  become_user: pacaur-builder
  aur:
    name: my-aur-package
```

ansible-aur should take care of this extra setup automatically in order to avoid the extra verbosity and to make the examples on README.md work again.

[1]: https://docs.ansible.com/ansible/become.html
[2]: https://bugs.archlinux.org/task/43302
